name: firebase_emulator_suite_sample
description: Simple Flutter app using Firebase Emulator Suite
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  firebase_storage: ^10.0.4
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_spinkit: ^5.0.0
  freezed_annotation: ^0.14.2
  gap: ^2.0.0
  get_it: ^7.2.0
  provider: ^6.0.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
